/**
 * Serialize `LayoutOverrides` back into something a developer can paste into
 * `src/lib/pdf/wh347Layout.ts`. Two flavors:
 *
 *  - `exportTsPatch` emits only the leaf properties that were touched, grouped
 *    by their layout constant block (e.g. `HEADER_P1`, `ROW_X`). Row-specific
 *    overrides are emitted as separate `LAYOUT_OVERRIDES["ROW_X.netPay@row=3"]`
 *    entries since they don't live on a constant.
 *  - `exportJson` is the raw map - good for sharing between machines.
 */

import { buildRegistry, stripRowSuffix, type LayoutOverrides, type AnchorPatch } from "../lib/pdf/anchorRegistry";

function fmt(n: number): string {
  // Render integers as integers, halves as .5, otherwise up to 2 decimals.
  const rounded = Math.round(n * 100) / 100;
  return Number.isInteger(rounded) ? String(rounded) : String(rounded);
}

function formatPatch(patch: AnchorPatch): string {
  const parts: string[] = [];
  if (patch.x != null) parts.push(`x: ${fmt(patch.x)}`);
  if (patch.y != null) parts.push(`y: ${fmt(patch.y)}`);
  if (patch.width != null) parts.push(`width: ${fmt(patch.width)}`);
  if (patch.height != null) parts.push(`height: ${fmt(patch.height)}`);
  return `{ ${parts.join(", ")} }`;
}

/**
 * Emit only the deltas as a `LAYOUT_OVERRIDES` map. Stable order: sorted by
 * key so diffs across runs stay readable.
 */
export function exportTsOverrides(overrides: LayoutOverrides): string {
  const keys = Object.keys(overrides).sort();
  if (keys.length === 0) {
    return "// No overrides yet. Drag anchors on /dev.html to start tuning.\nexport const LAYOUT_OVERRIDES = {} as const;\n";
  }
  const lines = ["import type { LayoutOverrides } from \"./anchorRegistry\";", ""];
  lines.push("// Generated by /dev.html. Paste into src/lib/pdf/wh347Layout.ts");
  lines.push("// (or import and pass to fillWh347 via options.overrides).");
  lines.push("export const LAYOUT_OVERRIDES: LayoutOverrides = {");
  for (const k of keys) {
    lines.push(`  "${k}": ${formatPatch(overrides[k]!)},`);
  }
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

/**
 * Emit replacements for whole layout-constant blocks touched by overrides.
 * Useful when you're ready to commit the change permanently to
 * `wh347Layout.ts`. Row-specific overrides (`@row=`) are emitted separately
 * because they don't fit any single constant slot.
 */
export function exportTsPatch(overrides: LayoutOverrides): string {
  const registry = buildRegistry();
  const byId = new Map(registry.map((a) => [a.id, a]));

  type GroupEntry = {
    x: number;
    y: number;
    width: number;
    height?: number;
    /** True when this group's base constants are shared across rows (no y/height). */
    rowTemplated: boolean;
  };

  const groups = new Map<string, Map<string, GroupEntry>>();
  const rowSpecific: [string, AnchorPatch][] = [];

  for (const [id, patch] of Object.entries(overrides)) {
    if (id.includes("@row=")) {
      rowSpecific.push([id, patch]);
      continue;
    }
    // Shared key: anchor is registered as `{group}.{key}@row=0` for row-only
    // templated groups (ROW_X.*, APPRENTICE.*), or `{group}.{key}@row=0&...`
    // for row+sub-index groups (DAY_X.* uses `@row=0&day=N`). Try all three
    // shapes so DAY_X shared keys (e.g. `DAY_X.st@day=6`) resolve too.
    const anchor =
      byId.get(id) ??
      byId.get(`${id}@row=0`) ??
      (id.includes("@") ? byId.get(id.replace(/@/, "@row=0&")) : undefined);
    if (!anchor) continue;
    const rowTemplated = anchor.id.includes("@row=");
    const merged: GroupEntry = {
      x: patch.x ?? anchor.x,
      y: patch.y ?? anchor.y,
      width: patch.width ?? anchor.width,
      height: patch.height ?? anchor.height,
      rowTemplated,
    };
    const bucket = groups.get(anchor.group) ?? new Map<string, GroupEntry>();
    bucket.set(anchor.key, merged);
    groups.set(anchor.group, bucket);
  }

  const out: string[] = [];
  out.push("// Paste each block below over the matching block in src/lib/pdf/wh347Layout.ts.");
  out.push("// Only groups touched by overrides are emitted.");
  out.push("");

  for (const [group, entries] of [...groups.entries()].sort()) {
    out.push(`// --- ${group} ---`);
    out.push(`export const ${group}_PATCH = {`);
    for (const [key, v] of [...entries.entries()].sort()) {
      const parts: string[] = [`x: ${fmt(v.x)}`, `width: ${fmt(v.width)}`];
      if (!v.rowTemplated) {
        // Non-templated groups (HEADER_P1, HEADER_P2, SIGNATURE_BLOCK, ...)
        // have absolute y/height. Row-templated groups (ROW_X, DAY_X) tile
        // the same x/width across multiple per-row y values, so y/height
        // belong to the row, not the shared constant.
        parts.splice(1, 0, `y: ${fmt(v.y)}`);
        if (v.height != null) parts.push(`height: ${fmt(v.height)}`);
      }
      out.push(`  ${key}: { ${parts.join(", ")} },`);
    }
    out.push("};");
    out.push("");
  }

  if (rowSpecific.length > 0) {
    out.push("// Row-specific overrides (apply via LAYOUT_OVERRIDES at runtime):");
    out.push("export const ROW_SPECIFIC_OVERRIDES = {");
    for (const [id, patch] of rowSpecific.sort((a, b) => a[0].localeCompare(b[0]))) {
      out.push(`  "${id}": ${formatPatch(patch)},`);
    }
    out.push("};");
    out.push("");
  }

  if (groups.size === 0 && rowSpecific.length === 0) {
    return "// No overrides yet. Drag anchors on /dev.html to start tuning.\n";
  }
  return out.join("\n");
}

export function exportJson(overrides: LayoutOverrides): string {
  // Sort keys for deterministic diffs.
  const sorted: LayoutOverrides = {};
  for (const k of Object.keys(overrides).sort()) sorted[k] = overrides[k]!;
  return JSON.stringify(
    {
      $note:
        "WH-347 layout overrides exported from /dev.html. Apply via fillWh347(..., { overrides }).",
      $generatedAt: new Date().toISOString(),
      overrides: sorted,
    },
    null,
    2,
  );
}

export function importJson(text: string): LayoutOverrides {
  const parsed = JSON.parse(text);
  const raw = parsed?.overrides ?? parsed;
  if (!raw || typeof raw !== "object") throw new Error("Invalid JSON payload.");
  const out: LayoutOverrides = {};
  for (const [k, v] of Object.entries(raw)) {
    if (!v || typeof v !== "object") continue;
    const patch: AnchorPatch = {};
    const vobj = v as Record<string, unknown>;
    for (const field of ["x", "y", "width", "height"] as const) {
      const n = vobj[field];
      if (typeof n === "number" && Number.isFinite(n)) patch[field] = n;
    }
    if (Object.keys(patch).length > 0) out[k] = patch;
  }
  return out;
}

/** Strip overrides whose values match the base registry (i.e. no-op edits). */
export function pruneOverrides(overrides: LayoutOverrides): LayoutOverrides {
  const registry = buildRegistry();
  const byId = new Map(registry.map((a) => [a.id, a]));
  const out: LayoutOverrides = {};
  for (const [id, patch] of Object.entries(overrides)) {
    // Shared key fallback shapes mirror exportTsPatch:
    //   exact id   -> matches non-templated anchors (HEADER_P1.projectName)
    //   `${id}@row=0`  -> matches row-only templated (ROW_X.netPay)
    //   inject `@row=0&` into the existing `@` -> matches row+sub (DAY_X.st@day=N)
    const target = id.includes("@row=")
      ? byId.get(id)
      : byId.get(id) ??
        byId.get(`${id}@row=0`) ??
        (id.includes("@") ? byId.get(id.replace(/@/, "@row=0&")) : undefined);
    const base = target ?? null;
    if (!base) continue;
    const slim: AnchorPatch = {};
    if (patch.x != null && approxNotEqual(patch.x, base.x)) slim.x = patch.x;
    if (patch.y != null && approxNotEqual(patch.y, base.y)) slim.y = patch.y;
    if (patch.width != null && approxNotEqual(patch.width, base.width)) slim.width = patch.width;
    if (patch.height != null && approxNotEqual(patch.height, base.height)) slim.height = patch.height;
    if (Object.keys(slim).length > 0) out[id] = slim;
  }
  return out;
}

function approxNotEqual(a: number, b: number): boolean {
  return Math.abs(a - b) > 0.0001;
}

export { stripRowSuffix };
